apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "signal-source.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "signal-source.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "signal-source.name" . }}
    spec:
      containers:
        - name: signal-source
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - secretRef:
                name: mongodb-secret
            - configMapRef:
                name: mongodb-config

          env:
            - name: MONGO_DB
              value: {{ .Values.env.MONGO_DB | quote }}
            - name: SIMULATION_URL
              value: {{ .Values.env.SIMULATION_URL | quote }}
