apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGO_USERNAME: {{ .Values.username | required "Missing MONGO_USERNAME" }}
  MONGO_PASSWORD: {{ .Values.password | required "Missing MONGO_PASSWORD" }}
