replicaCount: 1

image:
  repository: frontend
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

fullnameOverride: frontend
env:
  VITE_SIMULATION_BASE: /api/simulation
  VITE_SIGNAL_SOURCE_BASE: /api/signals
  VITE_LOCATOR_BASE: /api/locator

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
