replicaCount: 1

image:
  repository: simulation
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
fullnameOverride: simulation

env:
  MONGO_URI: mongodb://mongouser:mongopass@mongodb:27017/triangle?authSource=admin
  MONGO_DB: triangle
