apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: VITE_SIMULATION_BASE
              value: {{ .Values.env.VITE_SIMULATION_BASE | quote }}
            - name: VITE_SIGNAL_SOURCE_BASE
              value: {{ .Values.env.VITE_SIGNAL_SOURCE_BASE | quote }}
            - name: VITE_LOCATOR_BASE
              value: {{ .Values.env.VITE_LOCATOR_BASE | quote }}

