apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "local" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTLP_GRPC_PORT
              value: "4317"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(HOST_IP):$(OTLP_GRPC_PORT)"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "grpc"
            - name: OTEL_SERVICE_NAME
              value: {{ include "frontend.fullname" . }}
            - name: OTEL_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OTEL_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: >-
                service.name=$(OTEL_SERVICE_NAME),
                k8s.namespace.name=$(OTEL_K8S_NAMESPACE),
                k8s.node.name=$(OTEL_K8S_NODE_NAME),
                k8s.pod.name=$(OTEL_K8S_POD_NAME),
                k8s.container.name={{ .Chart.Name }},
                host.name=$(OTEL_K8S_NODE_NAME),
                deployment.environment=$(OTEL_K8S_NAMESPACE)
            - name: VITE_SIMULATION_BASE
              value: {{ .Values.env.VITE_SIMULATION_BASE | quote }}
            - name: VITE_SIGNAL_SOURCE_BASE
              value: {{ .Values.env.VITE_SIGNAL_SOURCE_BASE | quote }}
            - name: VITE_LOCATOR_BASE
              value: {{ .Values.env.VITE_LOCATOR_BASE | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

