apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "world-simulator.fullname" . }}
  labels:
    {{- include "world-simulator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "world-simulator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "world-simulator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: world-simulator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VITE_BASE_TOWER_URL
              value: {{ .Values.baseTower.url | quote }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
