
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.global.namespace | default "default" }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /api/simulation
            pathType: Prefix
            backend:
              service:
                name: simulation
                port:
                  number: 8000

          - path: /api/signals
            pathType: Prefix
            backend:
              service:
                name: signal-source
                port:
                  number: 8000

          - path: /api/locator
            pathType: Prefix
            backend:
              service:
                name: locator
                port:
                  number: 8000

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
