apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "locator.fullname" . }}
  labels:
    app: {{ include "locator.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "locator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "locator.name" . }}
    spec:
      containers:
        - name: locator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: {{ .Values.env.MONGO_URI | quote }}
