apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "locator.fullname" . }}
  labels:
    app: {{ include "locator.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "locator.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "locator.name" . }}
    spec:
      shareProcessNamespace: true
      containers:
        - name: locator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: {{ .Values.env.MONGO_URI | quote }}
            - name: OTEL_SERVICE_NAME
              value: "locator-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"
        - name: otel-auto-instrumentation
          image: otel/autoinstrumentation-go:latest
          imagePullPolicy: Always
          env:
            - name: OTEL_GO_AUTO_TARGET_EXE
              value: "/app/locator"
            - name: OTEL_SERVICE_NAME
              value: "locator-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"
          securityContext:
            privileged: true
          volumeMounts:
            - name: app-volume
              mountPath: /app
      volumes:
        - name: app-volume
          emptyDir: {}
