replicaCount: 1

image:
  repository: signal-source
  tag: local
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8000

nameOverride: ""
fullnameOverride: ""

opentelemetry:
  enabled: true
  serviceName: signal-source
  exporter:
    endpoint: otel-collector:4317
    protocol: grpc
    timeout: 10s
  traces:
    exporter: "otlp"
    sampler: "parentbased_always_on"
  metrics:
    exporter: "otlp"
  logs:
    exporter: "otlp"
  instrumentation:
    enabled: true
    serviceName: signal-source
    exporter:
      endpoint: otel-collector:4317
      protocol: grpc
      timeout: 10s
  resourceAttributes:
    service.name: "signal-source"

env:
  MONGO_USERNAME: mongouser
  MONGO_PASSWORD: mongopass
  MONGO_DB: triangle
  SIMULATION_URL: http://simulation:8000/signal

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
