replicaCount: 1

image:
  repository: signal-source
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

env:
  MONGO_USERNAME: mongouser
  MONGO_PASSWORD: mongopass
  MONGO_DB: triangle
  SIMULATION_URL: http://simulation:8000/signal

resources: {}
