apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simulation.fullname" . }}
  labels:
    app: {{ include "simulation.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simulation.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "simulation.name" . }}
    spec:
      containers:
        - name: simulation
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: {{ .Values.env.MONGO_URI | quote }}
            - name: MONGO_DB
              value: {{ .Values.env.MONGO_DB | quote }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

