apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp/http:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
                - "*"
              allowed_headers:
                - "*"

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      attributes:
        actions:
          - key: deployment.environment
            value: production
            action: insert
      resource:
        attributes:
          - key: service.namespace
            value: triangle
            action: insert

    exporters:
      datadog:
        api:
          key: ${DD_API_KEY}
          site: ${DD_SITE}
      debug:
        verbosity: detailed
      logging:
        sampling_initial: 1
        sampling_thereafter: 1
        loglevel: debug

    service:
      telemetry:
        logs:
          level: debug
          development: true
          encoding: console
      pipelines:
        traces:
          receivers: [otlp/http]
          processors: [batch, attributes, resource]
          exporters: [datadog, debug, logging]
        metrics:
          receivers: [otlp/http]
          processors: [batch, attributes, resource]
          exporters: [datadog, debug, logging]
